---
#
# Small binary sensor to tell me if someone is showering.
#
binary_sensor:
  - name: Is Showering
    unique_id: "189f7a87-46eb-4158-a403-4d55767e394e"
    icon: "mdi:shower-head"
    state: >-
      {{
        states('sensor.bath1_humidity_derivative')|int(0) > 5
      }}
