---
#
# Small binary sensor to tell me if I'm currently working
#
binary_sensor:
  - name: is_working
    unique_id: "dd34c680-4789-433d-8f61-55331c1e6780"
    icon: "mdi:briefcase"
    state: >
      {{
         is_state('binary_sensor.work_day', 'on')
         and is_state('binary_sensor.work_hours', 'on')
         and is_state('input_boolean.mode_vacation', 'off')
         and is_state('binary_sensor.holiday', 'off')
      }}
