---
#
# Small sensor which contains the time I must wake up.
#
sensor:
  - name: Wakeup time
    unique_id: "7089fa05-13a7-4dc0-85fa-b1d38eec8948"
    icon: "mdi:clock"
    state: |-
      {% if is_state('binary_sensor.must_work_today', 'on') %}
        {{ states('input_datetime.wakeup_time_workday') }}
      {% else %}
        {{ states('input_datetime.wakeup_time') }}
      {% endif %}
