---
#
# Small sensor which calculates the remaining dates
# until the next event.
#
sensor:
  - name: Days until trash blue
    unique_id: "8fa7ac95-cf67-4f4d-a129-a7d37e64cacf"
    icon: "mdi:trash-can"
    state: >-
      {{
        ((state_attr('calendar.trash_blue', 'start_time')
        | as_datetime | as_local).date() - now().date()).days
      }}
