---
#
# Small sensor which calculates the remaining dates
# until the next event.
#
sensor:
  - name: Days until trash rest
    unique_id: "3018303c-ee5a-4b71-b1d7-c6e444d2bd14"
    icon: "mdi:trash-can"
    state: >-
      {{
        ((state_attr('calendar.trash_rest', 'start_time')
        | as_datetime | as_local).date() - now().date()).days
      }}
