---
#
# Small sensor which contains names of open doors.
#
sensor:
  - name: Open doors
    unique_id: "3ee4701c-9701-4c4d-a1f7-499796ad1745"
    icon: "mdi:door-open"
    state: |-
      {% for door in states.binary_sensor.all_doors.attributes.entity_id if is_state(door, 'on') %}
      - {{ states[door].attributes.friendly_name }}
      {% endfor %}
