---
#
# Small sensor which contains names of open windows.
#
# trigger:
#   - platform: state
#     entity_id: binary_sensor.all_windows

sensor:
  - name: Open windows
    unique_id: "170ae53a-02bf-4882-bf3d-1b391cabae43"
    icon: "mdi:window-open"
    state: |-
      {% for window in states.binary_sensors.all_windows.attributes.entity_id if is_state(window, 'on') %}
        {{ window.name }}
      {% endfor %}
