---
#
# Small sensor which contains names of open windows.
#

sensor:
  - name: Open windows
    unique_id: "170ae53a-02bf-4882-bf3d-1b391cabae43"
    icon: "mdi:window-open"
    state: |-
      {% for window in states.binary_sensor.all_windows.attributes.entity_id if is_state(window, 'on') %}
      - {{ states[window].attributes.friendly_name }}
      {% endfor %}
