---
#
# Small sensor which calculates the remaining dates
# until the next event.
#
sensor:
  - name: Days until trash yellow
    unique_id: "c5267258-06a5-44c1-a337-778686f43948"
    icon: "mdi:trash-can"
    state: >-
      {{
        ((state_attr('calendar.trash_yellow', 'start_time')
        | as_datetime | as_local).date() - now().date()).days
      }}
