---
#
# Small sensor which contains names of open doors.
#
trigger:
  - platform: state
    entity_id: binary_sensor.all_doors

sensor:
  - name: Open doors
    unique_id: "3ee4701c-9701-4c4d-a1f7-499796ad1745"
    icon: "mdi:door-open"
    state: >-
      {% set result = namespace(open_doors=[]) %}
      {% for door in states.binary_sensors.all_doors.attributes.entity_id if is_state(door, 'on') %}
        {% set result.open_doors = result.open_doors + [door.name] %}
      {% endfor %}
      {{ result.open_doors | join('\n') }}
