---
#
# Small sensor which contains names of areas which should
# not trigger the intrusion detection system.
#

sensor:
  - name: Skip security in areas
    unique_id: "64233e49-67e6-4a64-9795-42c5dbcd6247"
    icon: "mdi:transit-skip"
    state: |-
      {% set skiplist = [] %}
      {% if is_state('input_boolean.skip_security_in_bath1', 'on') %}
        {% set skiplist = skiplist + ["Bath 1"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_bath2', 'on') %}
        {% set skiplist = skiplist + ["Bath 2"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_bedroom', 'on') %}
        {% set skiplist = skiplist + ["Bedroom"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_entrance', 'on') %}
        {% set skiplist = skiplist + ["Entrance"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_garage', 'on') %}
        {% set skiplist = skiplist + ["Garage"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_kitchen', 'on') %}
        {% set skiplist = skiplist + ["Kitchen"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_living', 'on') %}
        {% set skiplist = skiplist + ["Living"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_lunch', 'on') %}
        {% set skiplist = skiplist + ["Lunch"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_office1', 'on') %}
        {% set skiplist = skiplist + ["Office 1"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_office2', 'on') %}
        {% set skiplist = skiplist + ["Office 2"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_storage', 'on') %}
        {% set skiplist = skiplist + ["Storage"] %}
      {% endif %}
      {% if is_state('input_boolean.skip_security_in_wintergarden', 'on') %}
        {% set skiplist = skiplist + ["Wintergarden"] %}
      {% endif %}
      {{ skiplist }}
