---
#
# Small sensor which calculates the remaining dates
# until the next event.
#
sensor:
  - name: Days until trash bio
    unique_id: "81a3572e-71d6-456d-8d1c-2689d4043e4d"
    icon: "mdi:trash-can"
    state: >-
      {{
        ((state_attr('calendar.trash_bio', 'start_time')
        | as_datetime | as_local).date() - now().date()).days
      }}
