---
# Bath2 powerplug manager automation
#
id: "9604a9d3-fab3-4a71-955b-5ed45d944a33"
alias: "Bath2 powerplug manager automation"
description: >-
  This automation turns the bath2 powerplug on and off based on some input dates.

trigger:
  - platform: time
    at: input_datetime.bath2_powerplug_activation
    id: Start
  - platform: time
    at: input_datetime.bath2_powerplug_deactivation
    id: Stop

action:
  - choose:
      - conditions:
          - alias: "Turn it on"
            condition: and
            conditions:
              - condition: trigger
                id: Start
              - condition: state
                entity_id: switch.bath2_powerplug
                state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.bath2_powerplug
      - conditions:
          - alias: "Turn il off"
            condition: and
            conditions:
              - condition: trigger
                id: Stop
              - condition: state
                entity_id: switch.bath2_powerplug
                state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.bath2_powerplug
