---
# This automation creates a notification on my phone and
# keeps it there until the reason is gone.
#
id: "3619ec5b-8463-449a-8bf0-5bac911b1ee4"
mode: parallel
max_exceeded: silent
alias: "Door open notification automation"
description: >-
  Send a notfication to my phone when the door is open.
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_door_contact
      - binary_sensor.entrance_door_contact
      - binary_sensor.storage_door1_contact
      - binary_sensor.storage_door2_contact
action:
  - variables:
      entity_tag: "{{ 'open_door_tag_' ~ trigger.entity_id }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(trigger.entity_id, 'on') }}"
        sequence:
          - service: notify.mobile_app_pixel4a
            data:
              title: "{{states[trigger.entity_id].attributes.friendly_name}} is open."
              message: >-
                Open since {{ states('sensor.time') }}
              data:
                notification_icon: "mdi:door-open"
                tag: "{{ entity_tag }}"
                sticky: "true"
                actions:
                  - action: "URI"
                    title: "Open"
                    uri: "entityId:{{trigger.entity_id}}"
      - conditions:
          - condition: template
            value_template: "{{ is_state(trigger.entity_id, 'off') }}"
        sequence:
          - service: notify.mobile_app_pixel4a
            data:
              message: "clear_notification"
              data:
                tag: "{{ entity_tag }}"
