---
# Door bell detection automation
#
# This automation detects if someone rang the door bell.
# I have an Siedle 611-01 device which has a mechanical
# bell inside. I put a vibration sensor inside which
# should detect if the bell is ringing.
#
id: "75b764af-1a7e-4443-b646-b9fb24c31bb0"
alias: "Door bell detection"

trigger:
  - platform: state
    entity_id: binary_sensor.entrance_door_bell
    to: "on"

action:
  - service: notify.mobile_app_pixel4a
    data:
      title: "The door bell just rang!"
      message: "Maybe it's important..."
      data:
        notification_icon: "mdi:bell-alert"
