---
# Entity unavailable detection automation
#
# This automation notifies me if an entity went unavailable.
#
id: "f8700e07-1e98-4c0e-bc76-72cb293811d9"
mode: parallel
max_exceeded: silent
alias: "Entity unavailable detection"
description: >-
  This automation notfies me if an entity went unavailable.

  But also it deletes the notification if the entity goes into normal state again. I don't care then...
trigger:
  - platform: state
    to: unavailable
  - platform: state
    from: unavailable
action:
  - variables:
      entity_tag: "{{ 'unavailable_tag_' ~ trigger.entity_id }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.new_state.state == 'unavailable' }}"
        sequence:
          - service: notify.mobile_app_pixel4a
            data:
              title: "Entity {{states[trigger.entity_id].attributes.friendly_name}} went unavailable."
              message: >-
                Whats wrong?
              data:
                tag: "{{ entity_tag }}"
                actions:
                  - action: "URI"
                    title: "Open {{trigger.entity_id}}"
                    uri: "entityId:{{trigger.entity_id}}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state == 'unavailable' }}"
        sequence:
          - service: notify.mobile_app_pixel4a
            data:
              message: "clear_notification"
              data:
                tag: "{{ entity_tag }}"
