---
# Entity unavailable detection automation
#
# This automation notifies me if an entity went unavailable.
#
id: f8700e07-1e98-4c0e-bc76-72cb293811d9
mode: parallel
max_exceeded: silent
alias: Entity unavailable detection
description: >-
  This automation notfies me if an entity went unavailable. But also it deletes the notification if the entity goes into normal
  state again. I don't care then...
trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >-
      {{
        trigger.event.data.new_state.state == 'unavailable'
        or trigger.event.data.old_state.state == 'unavailable'
      }}

variables:
  excluded_entities:
    - light.lunch_light1
    - select.lunch_light1_power_on_behavior
    - update.lunch_light1
    - light.lunch_light2
    - select.lunch_light2_power_on_behavior
    - update.lunch_light2
    - light.lunch_light3
    - select.lunch_light3_power_on_behavior
    - update.lunch_light3
    - light.bedroom_light1
    - select.bedroom_light1_power_on_behavior
    - update.bedroom_light1
    - light.bedroom_light2
    - select.bedroom_light2_power_on_behavior
    - update.bedroom_light2
    - light.bedroom_light3
    - select.bedroom_light3_power_on_behavior
    - update.bedroom_light3
    - light.bedroom_lights
    - button.lg_webos_tv_fa22_identify
    - media_player.lg_webos_tv_fa22
    - switch.lg_webos_tv_fa22_mute

action:
  - variables:
      entity_tag: "{{ 'unavailable_tag_' ~ trigger.event.data.entity_id }}"
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{
                trigger.event.data.new_state.state == 'unavailable'
                and trigger.event.data.entity_id not in excluded_entities
              }}
        sequence:
          - service: notify.mobile_app_pixel_7
            data:
              title: Entity {{states[trigger.event.data.entity_id].attributes.friendly_name}} went unavailable.
              message: >-
                Whats wrong?
              data:
                tag: '{{ entity_tag }}'
                actions:
                  - action: URI
                    title: Open {{trigger.event.data.entity_id}}
                    uri: entityId:{{trigger.event.data.entity_id}}
      - conditions:
          - condition: template
            value_template: >-
              {{
                trigger.event.data.old_state.state == 'unavailable'
                and trigger.event.data.entity_id not in excluded_entities
              }}
        sequence:
          - service: notify.mobile_app_pixel_7
            data:
              message: clear_notification
              data:
                tag: '{{ entity_tag }}'
