---
# High humidity in bath detection automation
#
# This automation detects a high humidity value in baths.
#
id: "6b0f392f-9afd-4db4-bde7-f961f5391ada"
mode: single
alias: "High humdity in baths detection"
description: |-
  This automation detects high humidity in my bathrooms.

  High humidity is bad because it can lead to mold. I
  should therefore always try to get it down to 50-60%.
  Most problematic for this problem are baths, because
  the humidity after taking is shower is usually very
  high.

variables:
  action_cooldown: "{{ 'COOLDOWN_' ~ context.id }}"
  high_humidity: "{{ states('input_number.bathroom_setting_humidity_high') | int }}"
  bath_sensors: &bath_sensors
    - sensor.bath1_temp_humidity
  high_bath_sensors: |-
    {% for i in bath_sensors %}
      {% if states(i) | int >= high_humidity %}
        - {{ states[i].attributes.friendly_name }} ({{ states[i] }}%)
      {% endif %}
    {% endfor %}

trigger:
  - platform: state
    entity_id: *bath_sensors

condition: "{{ high_bath_sensors != '' }}"

action:
  - service: notify.mobile_app_pixel4a
    data:
      title: "Some sensors with high humidity have been found!"
      message: |-
        The humidity of the following sensors are
        higher than {{high_humidity}}%:
          {{high_bath_sensors}}
      data:
        color: "yellow"
        notification_icon: "mdi:water-percent"
        actions:
          - action: "{{ action_cooldown }}"
            title: Ok, give me 15 mins
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_cooldown }}"
    timeout: "00:01:00"
    continue_on_timeout: false
  - delay: "00:15"
