---
# High humidity in garage detection automation
#
# This automation detects a high humidity value in my garage.
#
id: "b3cc80e4-4039-4052-81c9-f8c25b6bc07a"
mode: single
alias: "High humdity in garage detection"
description: |-
  This automation detects high humidity in my garage.

  High humidity is bad because it can lead to mold. I
  should therefore always try to get it down to 50-60%.

variables:
  high_humidity: "{{ states('input_number.garage_setting_humidity_high') | int | default(80) }}"
  garage_sensors: &garage_sensors
    - sensor.garage_temp_humidity
  high_humidity_sensors: |-
    {% for i in garage_sensors %}
      {% if states(i) | int >= high_humidity %}
        - {{ states[i].attributes.friendly_name }} ({{ states(i) }}%)
      {% endif %}
    {% endfor %}

trigger:
  - platform: state
    entity_id: *garage_sensors

condition: "{{ high_humidity_sensors != '' }}"

action:
  - variables:
      action_cooldown15: "{{ 'COOLDOWN15_' ~ context.id }}"
      action_cooldown60: "{{ 'COOLDOWN60_' ~ context.id }}"
      action_cooldown300: "{{ 'COOLDOWN300_' ~ context.id }}"
  - service: notify.mobile_app_pixel4a
    data:
      title: "Some sensors with high humidity have been found!"
      message: |-
        The humidity of the following sensors are
        higher than {{high_humidity}}%:
          {{high_humidity_sensors}}
      data:
        color: "yellow"
        notification_icon: "mdi:water-percent"
        actions:
          - action: "{{ action_cooldown15 }}"
            title: "15 mins"
          - action: "{{ action_cooldown60 }}"
            title: "1 h"
          - action: "{{ action_cooldown300 }}"
            title: "3 h"
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_cooldown15 }}"
        id: Option One
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_cooldown60 }}"
        id: Option Two
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_cooldown300 }}"
        id: Option Three
    timeout: "01:00:00"
    continue_on_timeout: false
  - choose:
      - conditions: "{{ wait.trigger.id == 'Option One' }}"
        sequence:
          - delay: "00:15"
      - conditions: "{{ wait.trigger.id == 'Option Two' }}"
        sequence:
          - delay: "01:00"
      - conditions: "{{ wait.trigger.id == 'Option Two' }}"
        sequence:
          - delay: "03:00"
