---
id: "68229927-07bf-4342-800b-20a291ce5ed5"
trace:
  stored_traces: 25
alias: Intercom to chime pipeline
description: >-
  Triggers the chime if the intercom gets pressed.
triggers:
  - trigger: state
    entity_id:
      - event.vordereingang_ding
    from: null
actions:
  - action: homeassistant.turn_on
    target:
      entity_id: switch.wohnzimmer_play_ding_sound
mode: single
