---
# Intrusion detection automation
#
# This automation detects suspicious activity and notifys me.
#
id: "cc881516-1e51-4b9c-9542-c4b261ac98c9"
mode: queued
max_exceeded: silent
trace:
  stored_traces: 25
alias: "Intrusion detection"
description: >-
  Detects unusual behaviour while I'm not at home.

  The following things are considered unusual:
    - A window was opened
    - A door was opened

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >-
      {{
        trigger.event.data.entity_id is match('^binary_sensor\.[a-z0-9_]+_(?:door|window)_contact')
        and trigger.event.data.old_state.state == 'off'
        and trigger.event.data.new_state.state == 'on'
        and (is_state('binary_sensor.people_home', 'off')
            or is_state('input_boolean.away_mode', 'on'))
      }}

action:
  - service: notify.mobile_app_pixel4a
    data:
      title: "Possible intrusion detected!"
      message: >-
        This entity triggered the automation: {{trigger.event.data.entity_id}}
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
        notification_icon: "mdi:alarm-light"
        color: red
        confirmation: true
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_received
    timeout: "00:00:15"
    continue_on_timeout: true
  - choose:
      - alias: "When notification wasnt received"
        conditions: "{{ not wait.completed }}"
        sequence:
          - alias: "Call phone via sip"
            service: hassio.addon_stdin
            data:
              addon: ad61c150_dss_voip
              input:
                call_sip_uri: !secret emergency_sip_uri
                message_tts: >-
                  Possible intrusion detected. The sensor {{states[trigger.event.data.entity_id].attributes.friendly_name}}
                  was triggered. Check out why.
