---
# Intrusion detection automation
#
# This automation detects suspicious activity and notifys me.
#
id: "cc881516-1e51-4b9c-9542-c4b261ac98c9"
mode: queued
max_exceeded: silent
alias: "Intrusion detection"
description: >-
  Detects unusual behaviour while I'm not at home.

  The following things are considered unusual:
    - A window was opened
    - A door was opened

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >-
      {{
        trigger.event.data.entity_id is match('^binary_sensor\.[a-z_]+_(?:door|window)_opening')
        and trigger.event.data.old_state == 'off'
        and trigger.event.data.new_state == 'on'
        and (is_state('binary_sensor.people_home', 'off')
            or is_state('input_boolean.away_mode', 'on'))
      }}

action:
  - service: notify.mobile_app_pixel4a
    data:
      title: "Possible intrusion detected!"
      message: >-
        This entity triggered the automation: {{trigger.event.data.event_id}}
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
        notification_icon: "mdi:alarm-light"
        color: red
