---
# I use this automation to toggle the powerplug in the bath which
# controls a little ofen.
#
id: "66c3956a-4dd6-4af0-8e5d-45354b8af18a"
alias: "Bath ofen switcher"

trigger:
  - platform: state
    entity_id: binary_sensor.bath1_window_contact

action:
  - choose:
      - conditions: "{{trigger.to_state.state == 'on'}}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: switch.bath1_powerplug
