---
# Office 1 light switcher automation
#
# This automation switches the lights on and off in
# my office.
#
id: "40c147c1-b3a1-4214-b002-7bf7d4af65d0"
alias: "Office 1 light switcher"
description: >-
  This automation tries to predict how much light I need
  in my office and sets up the lights as needed.

variables:
  office_devices: &office_devices
    - device_tracker.daniel_tower
    - device_tracker.daniel_laptop_arbeit

trigger:
  - platform: state
    entity_id:
      - binary_sensor.office1_door_contact
    from: "off"
    to: "on"
    id: Door opened
  - platform: state
    entity_id:
      - binary_sensor.office1_door_contact
    from: "on"
    to: "off"
    id: Door closed
  - platform: state
    entity_id:
      - binary_sensor.need_light
    to: "on"
    id: Need light
  - platform: state
    entity_id:
      - binary_sensor.need_light
    to: "off"
    id: Dont need light
  - platform: state
    entity_id: *office_devices
    from: "not_home"
    to: "home"
    id: Device turned on
  - platform: state
    entity_id: *office_devices
    from: "home"
    to: "not_home"
    id: Device turned off
  - platform: state
    entity_id: sensor.office1_chair_action
    id: Sat down

condition:
  - condition: state
    entity_id: input_boolean.office1_manage_lights
    state: "on"

action:
  - choose:
      - conditions:
          - alias: "Need light, I'm in the office, but its off"
            condition: and
            conditions:
              - condition: trigger
                id: Need light
              - condition: state
                entity_id: light.office1_light
                state: "off"
              - condition: state
                entity_id: *office_devices
                match: any
                state: "home"
        sequence:
          - alias: "Turn on the lights"
            service: light.turn_on
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Dont need light anymore, turn off the light"
            condition: and
            conditions:
              - condition: trigger
                id: Dont need light
              - condition: state
                entity_id: light.office1_light
                state: "on"
        sequence:
          - alias: "Turn off the lights"
            service: light.turn_off
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Device turned on, turn light off"
            condition: and
            conditions:
              - condition: trigger
                id: Device turned on
              - condition: state
                entity_id: input_boolean.office1_device_on_lights_off
                state: "on"
              - condition: state
                entity_id: light.office1_light
                state: "on"
        sequence:
          - alias: "Turn off the lights"
            service: light.turn_off
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Sat down, turn light off"
            condition: and
            conditions:
              - condition: trigger
                id: Sat down
              - condition: state
                entity_id: input_boolean.office1_when_sitting_lights_off
                state: "on"
              - condition: state
                entity_id: light.office1_light
                state: "on"
        sequence:
          - alias: "Turn off the lights"
            service: light.turn_off
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Door opened and need light"
            condition: and
            conditions:
              - condition: trigger
                id: Door opened
              - condition: state
                entity_id: *office_devices
                state: "not_home"
              - condition: state
                entity_id: binary_sensor.need_light
                state: "on"
        sequence:
          - alias: "Turn on the lights"
            service: light.turn_on
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Device turned off, I want to leave the room, so turn on the lights"
            condition: and
            conditions:
              - condition: trigger
                id: Device turned off
              - condition: state
                entity_id: binary_sensor.need_light
                state: "on"
              - condition: state
                entity_id: light.office1_light
                state: "off"
        sequence:
          - alias: "Turn on the lights"
            service: light.turn_on
            target:
              entity_id: light.office1_light
      - conditions:
          - alias: "Door closed, no device online, I therefore left the room"
            condition: and
            conditions:
              - condition: trigger
                id: Door closed
              - condition: state
                entity_id: *office_devices
                state: "not_home"
        sequence:
          - alias: "Turn off the lights"
            service: light.turn_off
            target:
              entity_id: light.office1_light
