---
# Thermostat switcher automation
#
# This automation switches the thermostats on and off
# when I turned the away mode on.
#
id: 62f17829-bce4-495f-b1d5-b6798a9281a1
alias: Thermostat switcher
description: >-
  When I turned on the away mode, I want all
  thermostats to be turned off.

  When I return, I want them to be in the old
  state again.

  And when I open a window, I want the thermostat to
  turn off as long as it is still open.

variables:
  all_thermostats: &all_thermostats
    - climate.bad
    - climate.buro_1
    - climate.buro_2
    - climate.esszimmer_1
    - climate.esszimmer_2
    - climate.schlafzimmer_1
    - climate.schlafzimmer_2
    - climate.wohnzimmer

trigger:
  - alias: Away mode turned on
    platform: state
    entity_id:
      - input_boolean.away_mode
    from: 'off'
    to: 'on'
    id: Away mode turned on
  - alias: Away mode turned off
    platform: state
    entity_id:
      - input_boolean.away_mode
    from: 'on'
    to: 'off'
    id: Away mode turned off
  - alias: People are home
    platform: state
    entity_id:
      - binary_sensor.people_home
    from: 'off'
    to: 'on'
    id: People are home
  - alias: Office 1 window opened
    platform: state
    entity_id:
      - binary_sensor.office1_window_contact
    from: 'off'
    to: 'on'
    id: Office 1 window opened
    for: 00:00:10
  - alias: Office 1 window closed
    platform: state
    entity_id:
      - binary_sensor.office1_window_contact
    from: 'on'
    to: 'off'
    id: Office 1 window closed
  - alias: Lunch door opened
    platform: state
    entity_id:
      - binary_sensor.lunch_door_contact
    from: 'off'
    to: 'on'
    id: Lunch door opened
    for: 00:00:10
  - alias: Lunch door closed
    platform: state
    entity_id:
      - binary_sensor.lunch_door_contact
    from: 'on'
    to: 'off'
    id: Lunch door closed
  - alias: Bath1 window opened
    platform: state
    entity_id:
      - binary_sensor.bath1_window_contact
    from: 'off'
    to: 'on'
    id: Bath1 window opened
    for: 00:00:10
  - alias: Bath1 window closed
    platform: state
    entity_id:
      - binary_sensor.bath1_window_contact
    from: 'on'
    to: 'off'
    id: Bath1 window closed
  - alias: Bedroom window opened
    platform: state
    entity_id:
      - binary_sensor.bedroom_window_contact
      - binary_sensor.bedroom_door_contact
    from: 'off'
    to: 'on'
    id: Bedroom window opened
    for: 00:00:10
  - alias: Bedroom window closed
    platform: state
    entity_id:
      - binary_sensor.bedroom_window_contact
      - binary_sensor.bedroom_door_contact
    from: 'on'
    to: 'off'
    id: Bedroom window closed
  - alias: Time check
    platform: time_pattern
    minutes: /3
    id: Time check

action:
  - choose:
      - conditions:
          - alias: Office 1 window opened
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Office 1 window opened
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - binary_sensor.office1_window_contact
                        state: 'on'
              - condition: state
                entity_id:
                  - climate.buro_1
                state: heat
        sequence:
          - service: scene.create
            data:
              scene_id: office1_thermostat
              snapshot_entities:
                - climate.buro_1
          - alias: Turn off the thermostat
            service: climate.turn_off
            target:
              entity_id:
                - climate.buro_1
      - conditions:
          - alias: Office 1 window closed again
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Office 1 window closed
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - input_boolean.away_mode
                        state: 'off'
                      - condition: state
                        entity_id:
                          - binary_sensor.office1_window_contact
                        state: 'off'
              - condition: state
                entity_id:
                  - climate.buro_1
                state: 'off'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.office1_thermostat
      - conditions:
          - alias: Lunch door opened
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Lunch door opened
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - binary_sensor.lunch_door_contact
                        state: 'on'
              - condition: state
                entity_id:
                  - climate.wohnzimmer
                  - climate.esszimmer_1
                  - climate.esszimmer_2
                match: any
                state: heat
        sequence:
          - service: scene.create
            data:
              scene_id: lunch_living_thermostat
              snapshot_entities:
                - climate.wohnzimmer
                - climate.esszimmer_1
                - climate.esszimmer_2
          - alias: Turn off the thermostat
            service: climate.turn_off
            target:
              entity_id:
                - climate.wohnzimmer
                - climate.esszimmer_1
                - climate.esszimmer_2
      - conditions:
          - alias: Lunch door closed again
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Lunch door closed
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - input_boolean.away_mode
                        state: 'off'
                      - condition: state
                        entity_id:
                          - binary_sensor.lunch_door_contact
                        state: 'off'
              - condition: state
                entity_id:
                  - climate.wohnzimmer
                  - climate.esszimmer_1
                  - climate.esszimmer_2
                state: 'off'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.lunch_living_thermostat
      - conditions:
          - alias: Bath1 window opened
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Bath1 window opened
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - binary_sensor.bath1_window_contact
                        state: 'on'
              - condition: state
                entity_id:
                  - climate.bad
                state: heat
        sequence:
          - service: scene.create
            data:
              scene_id: bad_thermostat
              snapshot_entities:
                - climate.bad
          - alias: Turn off the thermostat
            service: climate.turn_off
            target:
              entity_id:
                - climate.bad
      - conditions:
          - alias: Bath1 window closed again
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Bath1 window closed
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - input_boolean.away_mode
                        state: 'off'
                      - condition: state
                        entity_id:
                          - binary_sensor.bath1_window_contact
                        state: 'off'
              - condition: state
                entity_id:
                  - climate.bad
                state: 'off'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bad_thermostat
      - conditions:
          - alias: Bedroom window opened
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Bedroom window opened
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - binary_sensor.bedroom_window_contact
                          - binary_sensor.bedroom_door_contact
                        state: 'on'
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - binary_sensor.bath1_window_contact
                        state: 'on'
                      - condition: state
                        entity_id:
                          - input_boolean.combine_bath_and_bedroom
                        state: 'on'
              - condition: state
                entity_id:
                  - climate.schlafzimmer_1
                  - climate.schlafzimmer_2
                match: any
                state: heat
        sequence:
          - service: scene.create
            data:
              scene_id: bedroom_thermostat
              snapshot_entities:
                - climate.schlafzimmer_1
                - climate.schlafzimmer_2
          - alias: Turn off the thermostat
            service: climate.turn_off
            target:
              entity_id:
                - climate.schlafzimmer_1
                - climate.schlafzimmer_2
      - conditions:
          - alias: Bedroom window closed again
            condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Bedroom window closed
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - input_boolean.away_mode
                        state: 'off'
                      - condition: state
                        entity_id:
                          - binary_sensor.bedroom_window_contact
                          - binary_sensor.bedroom_door_contact
                        state: 'off'
                  - condition: and
                    conditions:
                      - condition: trigger
                        id: Time check
                      - condition: state
                        entity_id:
                          - input_boolean.away_mode
                        state: 'off'
                      - condition: state
                        entity_id:
                          - binary_sensor.bath1_window_contact
                        state: 'off'
                      - condition: state
                        entity_id:
                          - input_boolean.combine_bath_and_bedroom
                        state: 'on'
              - condition: state
                entity_id:
                  - climate.schlafzimmer_1
                  - climate.schlafzimmer_2
                state: 'off'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bedroom_thermostat
      - conditions:
          - alias: Away mode turned on
            condition: and
            conditions:
              - condition: trigger
                id: Away mode turned on
              - condition: state
                entity_id: *all_thermostats
                match: any
                state: heat
        sequence:
          - service: scene.create
            data:
              scene_id: before
              snapshot_entities: *all_thermostats
          - alias: Turn off the thermostats
            service: climate.turn_off
            target:
              entity_id: *all_thermostats
      - conditions:
          - alias: Away mode turned off
            condition: and
            conditions:
              - condition: trigger
                id: Away mode turned off
              - condition: state
                entity_id: *all_thermostats
                match: any
                state: 'off'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.before
      - conditions:
          - condition: trigger
            id: People are home
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.away_mode
